defaults:
  - dataset_list.yaml
  - model_list.yaml

run:
  seed: 42
  n_rows: 5_000 # rows per dataset split
  batch_size: 128
  num_workers: 4
  overwrite: false # if true, overwrite existing embeddings; if false, skip if files exist

output:
  adata_cache: ${hydra:runtime.cwd}/data/from_nxtcloud
  root: ${hydra:runtime.cwd}/out/embeddings
  format: parquet # csv | parquet

slurm:
  store_id: true # if true add SLURM_JOB_ID to metadata

hydra:
  run:
    dir: ${hydra:runtime.cwd}/runs/${now:%Y-%m-%d}/${now:%H-%M-%S}
