# conf/config.yaml

# The embedding_dim_map is used to derive embedding_dim based on embedding_method.
# You can override embedding_method from the command line:
#   python train.py embedding_method=hvg
#
# Or you can override any other parameter by specifying its full path, e.g.:
#   python train.py dataset.basename=my_awesome_dataset

# Here are some defaults:
embedding_method: "scvi" #This refers to the precomputed "embeddings" in .obsm of the anndata object accessible throgh the sharelink in the dataset

input_dim_map:
  hvg: 2000
  pca: 64
  scvi: 64
  geneformer: 512

dataset:
  basename: "geo_7k_cellxgene_3_5K"
  type: "pairs"
  test_datasets:
    - "jo-mengr/bowel_disease_single"

text_encoder:
  name: "pritamdeka/S-BioBert-snli-multinli-stsb"
  freeze_text_encoder: True
  unfreeze_last_n_layers: 0

#loss: "MultipleNegativesRankingLoss"
#loss: "ContrastiveLoss"
#evaluator: "TripletEvaluator" # If not provided, the default evaluator is used

adapter:
  omics_input_dim: None #this will be overwritten by the embedding_dim_map
  hidden_dim: 512
  output_dim: 1024

trainer:
  unfreeze_epoch: 0.03
  output_dir: "../../models/trained"
  num_train_epochs: 32
  per_device_train_batch_size: 16
  per_device_eval_batch_size: 16
  learning_rate: 2e-5
  warmup_ratio: 0.1
  fp16: false
  bf16: false
  eval_strategy: "steps"
  eval_steps: 100
  save_strategy: "steps"
  save_steps: 500
  save_total_limit: 2
  logging_steps: 100

save_dir: "out"
# You could also define logging via Hydra’s logging config if desired,
# but here we do not override the default Hydra logging setup.
