#pp/default.yaml
general:
  train_size: 0.8
  # Consolidate or remove the following categories if they have less samples than the treshhold
  categories: ["cell_type", "dataset_id"]
  threshold: 5
  remove: True
embedder:
  context_embedder:
    use_precalculated: False
    precalculated_obsm_key: c_emb
    type: categorical # categorical currently the only option
  category_embedder:
    metadata_categories: ["cell_type"]
    one_hot: False
    model: text-embedding-3-small
    combination_method: concatenate
    embeddings_file_path: ${data.dir}/emb_dicts/category_embeddings_{.model}_metadata_embeddings.pkl.gz
  data_embedder:
    use_precalculated: True
    precalculated_obsm_key: scvi
    type: null
normalizer:
  type: null #min-max or z-score or null
aligner:
  latent_dim: 64
  type: pca
  pca_eval:
    evaluate_pca: False
    save_path: pca_eval
    scree_plot: True
    cumulative_variance_plot: True
    loadings_heatmap: True
    loadings_heatmap_options:
      threshold: 0 # Only include loadings above this threshold
      top_n_components: 64 # Number of principal components to include in the heatmap
      top_n_variables: 100 # Number of variables to display in the heatmap
dataset_constructor:
  seq_length: 12
  batch_size: 32
