defaults:
  - pp/default
  - override hydra/job_logging: default
  - override hydra/hydra_logging: default
data:
  dir: data
  sample_key: soma_joinid
  batch_key: dataset_id
  cell_type_key: cell_type
  train:
    subdir: ${data.dir}/raw/train
    filenames: [subset_large_cellxgene.h5ad, subset3_large_cellxgene.h5ad]
  test:
    subdir: ${data.dir}/raw/test
    filenames: [subset2_large_cellxgene.h5ad]
dataset:
  seq_length: 64 # eventhough the dataset is not created during preprocessing, the sequence length is used to determine the chunk size of zarr storage for efficiency
  batch_size: 32
  multiplier: 1 # Multiplied by the seq-length * batch_size to give the chunk size
  chunk_size: null # Overwrite in python scirpt

pp:
  embedder:
    context_embedder:
      type: categorical # Overriding context_embedder.type
    category_embedder:
      one_hot: True
      metadata_categories: ["cell_type"]
      combination_method: concatenate
    data_embedder:
      precalculated_obsm_key: "scvi"
  normalizer:
    type: "z-score"
  aligner:
    latent_dim: 64

  additional:
    pca_eval:
      evaluate_pca: True
